name: flex_with_main_child
description: A Flex (i.e. Column or Row) that sizes itself to its main child in the cross axis direction.
version: 0.2.1
repository: https://github.com/chomosuke/flex_with_main_child

environment:
  sdk: ">=2.17.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
